name: Rebuild

on: 
  push: {branches: [main]}

  # run once every month
  schedule: [{cron: "4 4 */2 * *"}]

  # enable manual runs
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyfiglet
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: execute py script 
        run: |
          python create-csv-and-geojson.py
      
      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v5
        with:
          path: data/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

      # In "Settings > Actions > General", Under "Workflow permissions" check "Allow GitHub Actions to create and approve pull requests"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8